<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGA.Domain\SGA.Domain.csproj" />
    <ProjectReference Include="..\SGA.Infrastructure\SGA.Infrastructure.csproj" />
    <ProjectReference Include="..\SGA.Model\SGA.Model.csproj" />
    <ProjectReference Include="..\SGA.Persistence\SGA.Persistence.csproj" />
  </ItemGroup>

</Project>
