<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGA.Application\SGA.Application.csproj" />
    <ProjectReference Include="..\SGA.Domain\SGA.Domain.csproj" />
    <ProjectReference Include="..\SGA.Infrastructure\SGA.Infrastructure.csproj" />
    <ProjectReference Include="..\SGA.Persistence\SGA.Persistence.csproj" />
  </ItemGroup>

</Project>
