<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGA.Application\SGA.Application.csproj" />
    <ProjectReference Include="..\SGA.Domain\SGA.Domain.csproj" />
    <ProjectReference Include="..\SGA.Infrastructure\SGA.Infrastructure.csproj" />
    <ProjectReference Include="..\SGA.IOC\SGA.IOC.csproj" />
    <ProjectReference Include="..\SGA.Persistence\SGA.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ClientApp\src\assets\" />
    <Folder Include="ClientApp\src\components\" />
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
