<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Forms\Auditoria\" />
    <Folder Include="Models\Autobus\" />
    <Folder Include="Models\Auditoria\" />
    <Folder Include="Models\Incidencia\" />
    <Folder Include="Models\Horario\" />
    <Folder Include="Models\Conductor\" />
    <Folder Include="Models\Viaje\" />
    <Folder Include="Models\Ruta\" />
    <Folder Include="Models\Parada\" />
    <Folder Include="Models\Usuario\" />
    <Folder Include="Controls\" />
    <Folder Include="Resources\Images\" />
    <Folder Include="Resources\Icons\" />
    <Folder Include="Resources\Logo\" />
    <Folder Include="Services\Auditoria\" />
    <Folder Include="Services\Incidencia\" />
    <Folder Include="Services\Usuario\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="System.Net.Http.Json" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGA.Application\SGA.Application.csproj" />
    <ProjectReference Include="..\SGA.Domain\SGA.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>