<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGA.Application\SGA.Application.csproj" />
    <ProjectReference Include="..\SGA.Domain\SGA.Domain.csproj" />
    <ProjectReference Include="..\SGA.Infrastructure\SGA.Infrastructure.csproj" />
    <ProjectReference Include="..\SGA.IOC\SGA.IOC.csproj" />
    <ProjectReference Include="..\SGA.Persistence.Test\SGA.Persistence.Test.csproj" />
    <ProjectReference Include="..\SGA.Persistence\SGA.Persistence.csproj" />
  </ItemGroup>

</Project>